POST http://localhost:3005/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imt1bGNzYXJtYWphQGdteC5jb20iLCJpZCI6MywiaWF0IjoxNjQzMzA1MDM3fQ.l5byfMfgLgC8tYgm3w0cidkU36capgWMaGQCfDkkzC8

{
    "title": "BTS",
    "url":"https://www.bts.com",
    "year": 2022,
    "likes": 1
}